# Generated by Django 2.1.2 on 2018-11-04 14:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_auto_20181104_1614'),
        ('courses', '0002_auto_20181104_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('examine_at', models.DateField(default=datetime.datetime(2018, 11, 4, 16, 17, 58, 845135))),
                ('degree', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
